# Redirects and rewrites settings (optional)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Basic build settings (optional)
[build]
  publish = "build" # Specify the directory to publish (default is "public" or "dist" for certain frameworks)
  command = "npm run build" # Specify the build command (default is "npm install && npm run build")

# Environment variables (optional)
# You can specify environment variables here if needed
# Example:
# [build.environment]
#   REACT_APP_API_KEY = "your_api_key"

# Headers configuration (optional)
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

# Functions directory (optional, for serverless functions)
# [functions]
#   directory = "netlify/functions"

# Asset optimization (optional)
# [build.processing]
#   css = { bundle: true, minify: true }
#   js = { bundle: true, minify: true, external: true }

# Custom domain (optional)
# [build.custom]
#   domain = "your-custom-domain.com"

# Proxy settings (optional, for API proxying)
# [build.proxy]
#   "/api" = "http://your-api-server.com"

# Identity settings (optional, for Netlify Identity)
# [build]
#   identity = "your-netlify-identity-instance-name"
